define([], function() {
    return {
        "PropertyPaneDescription": "Description",
        "BasicGroupName": "Group Name",
        "DescriptionFieldLabel": "Description Field",
        
        UseCorsFieldDescription: "Se você receber uma mensagem dizendo \" Falha ao buscar o URL do feed que você especificou. \", Tente habilitar a opção \" Usar proxy \".",
        ConvertFromUTCFieldDescription: "Se seu feed retornar eventos Universal Time Coordinated (UTC) e seus eventos aparecerem no fuso horário errado, tente ativar \" Converter de UTC \".",
        ConvertFromUTCOptionNo: "Do not convert",
        ConvertFromUTCOptionYes: "Convert",
        ConvertFromUTCLabel: "Converter de UTC",
        MaxTotalFieldDescription: "Indica o número total de eventos a serem carregados. Use 0 para no máximo.",
        MaxTotalFieldLabel: "Número máximo de eventos",
        FilmStripAriaLabel: "Lista de eventos. Use as setas esquerda e direita para mover entre os eventos. Pressione Enter para ir para o evento selecionado.",
        PropertyPaneDescription: "Selecione o tipo de feed ao qual deseja se conectar e o URL do feed.",
        AllItemsUrlFieldLabel: "Ver URL de todos os eventos",
        FeedUrlFieldLabel: "URL de feed",
        FeedTypeFieldLabel: "Tipo de feed",
        PlaceholderTitle: "Configurar feed de eventos",
        PlaceholderDescription: "Para exibir um resumo dos eventos, você precisa selecionar um tipo de feed e configurar o URL do feed do evento.",
        ConfigureButton: "Configure",
        FeedTypeOptionGoogle: "Google Agenda",
        FeedTypeOptioniCal: "iCal",
        FeedTypeOptionRSS: "Calendário RSS",
        FeedTypeOptionWordPress: "WordPress WP_FullCalendar",
        FeedUrlCallout: "Se seu feed for compatível com parâmetros de período, use {s} e {e} para as datas de início e término e nós os substituiremos por valores de data.",
        MaxEventsFieldLabel: "Narrow page length",
        MaxEventsFieldDescription: "Indica o número de eventos a serem mostrados por página ao exibir uma lista restrita. Use 0 para no máximo",
        DateRangeFieldLabel: "Período",
        DateRangeOptionUpcoming: "Próximo ano",
        DateRangeOptionWeek: "Próxima semana",
        DateRangeOptionTwoWeeks: "Próximas duas semanas",
        DateRangeOptionMonth: "Próximo mês",
        DateRangeOptionQuarter: "Próximo trimestre",
        UseCORSFieldLabel: "Usar proxy",
        UseCORSFieldCallout: "Habilite esta opção se você receber uma mensagem CORS",
        UseCORSFieldCalloutDisabled: "Esta opção é desabilitada ao usar o provedor Mock",

        CORSOn: "On",
        CORSOff: "Desligado",
        AdvancedGroupName: "Advanced",
        FocusZoneAriaLabelReadMode: "Lista de eventos. Use as teclas de seta para cima e para baixo para mover entre os eventos. Pressione Enter para obter os detalhes de um evento selecionado.",
        FocusZoneAriaLabelEditMode: "Lista de eventos. Use as setas para cima e para baixo para mover entre os eventos.",
        EventCardWrapperArialLabel: "Evento {0}. Comece em {1}.",
        Carregando: "Por favor espere...",
        NoEventsMessage: "Não há eventos futuros.",
        CacheDurationFieldLabel: "Cache duration (minutes)",
        CacheDurationFieldCallout: "Use 0 se não quiser armazenar eventos em cache. O valor máximo é 1 dia (14.400 minutos).",
        FeedUrlValidationNoUrl: "Forneça um URL",
        FeedUrlValidationInvalidFormat: "URL não é um formato válido. Use um URL que comece com http: // ou https: //.",
        ErrorMessage: "Ops, algo deu errado! Não podemos exibir seus eventos no momento. Tente novamente mais tarde.",
        NextButtonLabel: "Próximo",
        PrevButtonLabel: "Anterior",
        NextButtonAriaLabel: "Vá para a próxima página",
        PrevButtonAriaLabel: "Vá para a página anterior",
        ErrorNotFound: "O URL do feed que você especificou não pode ser encontrado. Verifique se você tem o URL correto e tente novamente.",
        ErrorMixedContent: "Falha ao buscar o URL do feed que você especificou. Tente usar um URL https: // ou habilite a opção \" Usar proxy \"",
        ErrorFailedToFetch: "Falha ao buscar o URL do feed que você especificou. Isso pode ser devido a um URL inválido.",
        ErrorFailedToFetchNoProxy: "Falha ao buscar o URL do feed que você especificou. Isso pode ser devido a um URL inválido ou um problema de CORS. Verifique o URL ou ative a opção \" Usar proxy \".",
        ErrorRssNoResult: "O feed que você especificou não parece ser um feed RSS",
        ErrorRssNoRoot: "O feed RSS que você especificou parece ser inválido: ele não tem uma raiz",
        ErrorRssNoChannel: "O feed RSS que você especificou parece ser inválido: ele não tem um canal",
        ErrorInvalidiCalFeed: "O URL fornecido não parece ser um feed iCal. Tem certeza de que selecionou o tipo de feed correto?",
        ErrorInvalidWordPressFeed: "O URL fornecido não parece ser um feed do WordPress. Tem certeza de que selecionou o tipo de feed correto?",
        AddToCalendarAriaLabel: "Pressione Enter para baixar o arquivo de calendário para o seu dispositivo.",
        AddToCalendarButtonLabel: "Adicionar à minha agenda",
        AllDayDateFormat: "dddd, MMMM Do YYYY",
        LocalizedTimeFormat: "llll",
        FeedSettingsGroupName: "Feed de calendário"

    }
  });